### ISSUE TITLE
imaging_table cannot find RunParameters.xml

### ISSUE THREAD

**Issue by mcgml** [Illumina/interop#79]
MiSeq V2 runs generate runParameters.xml while MiSeq V3 give RunParameters.xml using MCS v2.5.0.5. 

The imaging_table throws error with V2 runs: 
`RunParameters.xml required for legacy run folders with missing channel names
/share/apps/interop-distros/interop/./interop/model/run_metrics.h::read_run_parameters (187)`

Renaming the file solves the issue.

**Comment by ezralanglois** [comment]
Hi Matthew,
Thanks for the bug report. What version of the code are you using? If this is from master, what was the last commit?

This was a bug we had in the code that was fixed in April, but imaging_table was not added until June. This indicates that we missed an edge case, but so far I am unable to reproduce it. Know what version of the code you are using would help greatly.

**Comment by mcgml** [comment]
Hi Robert

Thanks for developing this really useful tool, it will make my life much easier!

Apologies for leaving that off. Yes, i'm using the latest commit from master (acquired last week). I had some troubles building v1.0.7 from source and was missing the required libc6 for the binary release. Let me know if that doesn't fit and i'll give it another try.

Thanks
Matt

**Comment by ezralanglois** [comment]
Hi Matt,

I downloaded our binary and tried it on a comparable dataset and was unable to reproduce the problem. I rebuilt it from master and was still unable to reproduce the problem.

These are the steps I went through:
1. Downloaded: https://github.com/Illumina/interop/releases/download/v1.0.8/interop-linux_gcc46_release.tar.gz

2. I ensured there was a runParameters.xml, not a RunParameters.xml and that there were no channel names in the RunInfo.xml in the run folder. This dataset should have come from the same type of instrument.

3. I repeated everything by cloning master and was still unable to reproduce the problem.

Based on what you said, I only tested on Linux (it sounds like you are using an older distro if the binary did not work).

If you are willing to share the RunInfo.xml and runParameters.xml, then I can check if there is some issue specific to your XML files. That said, I am at a loss as to why this is happening.

Best,
Rob

**Comment by mcgml** [comment]
Hi Robert

Thanks for investigating this further. I rebuilt from source this morning (master branch; Centos 6) but i'm still having the same issue. I've attached XML files, let me know if you need any more information.

[XML.zip](https://github.com/Illumina/interop/files/429868/XML.zip)

Cheers
Matt

**Comment by ezralanglois** [comment]
Hi Matt,

I appreciate you helping out with this. 

I took your files compared them to other MiSeq runs I have and I don't see anything strange about them. I used them in place of another set I had, and everything works fine with both RunParameters.xml and runParmeters.xml.

The only thing I can think of is that somehow your src/interop/model/run/parameters.cpp file is out of date. Could you attach that to this thread?

Also, another problem did occur to me. It does not match what you described above, but for older MiSeq runs, you could get the following error:
Unknown tile naming method - update your RunInfo.xml.

This is a known bug, that we plan to fix, but have not had the bandwidth to do it yet.

Best,
Rob

**Comment by mcgml** [comment]
Hi Rob

Thanks again for your reply. See attached cpp file as requested.

I haven't encountered the error you mentioned but i'll keep that in mind.

Thanks
Matt

[parameters.zip](https://github.com/Illumina/interop/files/431983/parameters.zip)

**Comment by ezralanglois** [comment]
Hi Matt,

I am running out of ideas as to why you are seeing this problem. The only thing I can think of is that this is a problem specific to Centos 6. I wanted to do the following but I need some information from you:
1. Set up my own Centos VM and try the code there
2. Give you a build that is compatible with your system

What is the version of CentOs (6.1, 6.2 etc.) that you are running and the version of g++?


Best,
Rob

**Comment by mcgml** [comment]
Hi Rob

Sorry for the slow reply. We're using Centos 6.5 and gcc 4.4.7. If it helps, its a Rocks setup (v6.1) available here: http://www.rocksclusters.org/wordpress/?page_id=477

Thanks
Matt

**Comment by ezralanglois** [comment]
Hi Matt,

Thanks, I have been out myself. I will setup a VM and see if I can reproduce the problem in these setup.

Best,
Rob

**Comment by ezralanglois** [comment]
Hi Matt,

I setup a Centos 6.5 VM and built the summary app. I was unable to reproduce the problem using latest master or versions as early as 1.0.9.

I attached the application so you can see if you have the same problem

file:///home/ipa/interop/build/src/apps/summary

Best,
Rob

**Comment by ezralanglois** [comment]
Here is the file:

[summary.zip](https://github.com/Illumina/interop/files/468107/summary.zip)

**Comment by mcgml** [comment]
Thanks again Rob. I tried your executable and still get the same error

```
$ ./summary  /data/archive/miseq/160901_M02641_0134_000000000-ATBYE
# Version: v1.0.10-5-g9210005
RunParameters.xml required for legacy run folders with missing channel names
/home/ipa/interop/src/interop/model/run_metrics.cpp::read_run_parameters (378)
```

Then I rename the file from RunParameters.xml to runParameters.xml I get 

```
$ ./summary /data/archive/miseq/160901_M02641_0134_000000000-ATBYE
# Version: v1.0.10-5-g9210005
 Level           Yield           Projected Yield Aligned         Error Rate      Intensity C1    %>=Q30         
 Read 1          1.91            1.91            1.46            0.19            196             97.07          
 Read 2 (I)      0.18            0.18            0.00            0.00            512             95.15          
 Read 3          1.91            1.91            1.43            0.28            231             95.66          
 Non-indexed     3.83            3.83            1.45            0.24            214             96.36          
 Total           4.01            4.01            1.45            0.24            313             96.31          


Read 1
 Lane            Tiles           Density         Cluster PF      Phas/Prephas    Reads           Reads PF        %>=Q30          Yield           Cycles Error    Aligned         Error           Error (35)      Error (75)      Error (100)     Intensity C1   
 1               38              1148 +/- 38     92.02 +/- 1.51  0.151 / 0.037   28.11           25.87           97.07           1.91            74              1.46 +/- 0.07   0.19 +/- 0.02   0.11 +/- 0.01   0.00 +/- 0.00   0.00 +/- 0.00   196 +/- 21     
Read 2 (I)
 Lane            Tiles           Density         Cluster PF      Phas/Prephas    Reads           Reads PF        %>=Q30          Yield           Cycles Error    Aligned         Error           Error (35)      Error (75)      Error (100)     Intensity C1   
 1               38              1148 +/- 38     92.02 +/- 1.51  0.000 / 0.000   28.11           25.87           95.15           0.18            0               0.00 +/- 0.00   0.00 +/- 0.00   0.00 +/- 0.00   0.00 +/- 0.00   0.00 +/- 0.00   512 +/- 61     
Read 3
 Lane            Tiles           Density         Cluster PF      Phas/Prephas    Reads           Reads PF        %>=Q30          Yield           Cycles Error    Aligned         Error           Error (35)      Error (75)      Error (100)     Intensity C1   
 1               38              1148 +/- 38     92.02 +/- 1.51  0.131 / 0.052   28.11           25.87           95.66           1.91            74              1.43 +/- 0.06   0.28 +/- 0.04   0.19 +/- 0.03   0.00 +/- 0.00   0.00 +/- 0.00   231 +/- 26     
Extracted: 158
Called: 158
Scored: 158
```

Its really strange you can't reproduce it. Perhaps you could have another go with these files?

[160901_M02641_0134_000000000-ATBYE.tar.gz](https://github.com/Illumina/interop/files/470089/160901_M02641_0134_000000000-ATBYE.tar.gz)


Let me know if there is anything else I can do.

Cheers
Matt

**Comment by ezralanglois** [comment]
Hi Matt,

Thanks. My colleague Nitin found the bug. I misunderstood the problem and was testing the wrong situation. My apologies.

We should have a bug fix out for this today.

Best,
Rob

**Comment by mcgml** [comment]
Great news, Thanks!

**Comment by mcgml** [comment]
Thanks Rob, all works well.

Matt
